In [3]:
import pandas as pd
import numpy as np

In [11]:
df_1=pd.DataFrame({"key":["a","b","c","d","e"],
                    "A":range(5),
                    "B":range(5,10)
    })

In [6]:
df_1

  key  A  b
0   a  0  5
1   b  1  6
2   c  2  7
3   d  3  8
4   e  4  9

In [15]:
df_2=pd.DataFrame({"key":["b","d","f"],
                   "C":range(3),
                   "D":range(3,6)
                  })

In [8]:
df_2

  key  C  D
0   b  0  3
1   d  1  4
2   f  2  5

In [21]:
pd.merge(df_1,df_2,how='inner',on='key')

  key  A  B  C  D
0   b  1  6  0  3
1   d  3  8  1  4

In [22]:
pd.merge(df_1,df_2,how='inner',on='key')[['key','A','D']]

  key  A  D
0   b  1  3
1   d  3  4

In [23]:
pd.merge(df_1,df_2,how="left",on="key")

  key  A  B    C    D
0   a  0  5  NaN  NaN
1   b  1  6  0.0  3.0
2   c  2  7  NaN  NaN
3   d  3  8  1.0  4.0
4   e  4  9  NaN  NaN

In [24]:
pd.merge(df_1,df_2,how="right",on="key")

  key    A    B  C  D
0   b  1.0  6.0  0  3
1   d  3.0  8.0  1  4
2   f  NaN  NaN  2  5

In [25]:
pd.merge(df_1,df_2,how="outer",on="key")

  key    A    B    C    D
0   a  0.0  5.0  NaN  NaN
1   b  1.0  6.0  0.0  3.0
2   c  2.0  7.0  NaN  NaN
3   d  3.0  8.0  1.0  4.0
4   e  4.0  9.0  NaN  NaN
5   f  NaN  NaN  2.0  5.0

In [26]:
df_3=pd.DataFrame({"key":["a","b","c","d","e"],
                    "A":range(5),
                    "B":range(5,10)
    })

In [27]:
df_4=pd.DataFrame({"key":["E","F","G","H","I"],
                    "A":range(10,15),
                    "B":range(2,7)
    })

In [29]:
df_4

  key   A  B
0   E  10  2
1   F  11  3
2   G  12  4
3   H  13  5
4   I  14  6

In [30]:
df_3

  key  A  B
0   a  0  5
1   b  1  6
2   c  2  7
3   d  3  8
4   e  4  9

In [33]:
pd.concat([df_4,df_3])

  key   A  B
0   E  10  2
1   F  11  3
2   G  12  4
3   H  13  5
4   I  14  6
0   a   0  5
1   b   1  6
2   c   2  7
3   d   3  8
4   e   4  9