In [1]:
import numpy as np
import pandas as pd

In [3]:
dff={
    "col_1":[1,2,3,4,5],
    "col_2":[111,222,333,111,555],
    "col_3":['alpha','bravo','charlie',np.nan,np.nan]
}
df=pd.DataFrame(dff)
df

   col_1  col_2    col_3
0      1    111    alpha
1      2    222    bravo
2      3    333  charlie
3      4    111      NaN
4      5    555      NaN

In [6]:
#unique value show korbe
print(df["col_1"].unique())
print(df["col_2"].unique())
print(df["col_3"].unique())

[1 2 3 4 5]
[111 222 333 555]
['alpha' 'bravo' 'charlie' nan]

In [7]:
#number of unique value dhekai

df["col_1"].nunique()

5

In [9]:
df["col_2"].value_counts()

col_2
111    2
222    1
333    1
555    1
Name: count, dtype: int64

In [10]:
df.sort_values(by='col_2')

   col_1  col_2    col_3
0      1    111    alpha
3      4    111      NaN
1      2    222    bravo
2      3    333  charlie
4      5    555      NaN

In [12]:
df.indexf

RangeIndex(start=0, stop=5, step=1)

In [13]:
df.columns

Index(['col_1', 'col_2', 'col_3'], dtype='object')

In [15]:
#insert new column in any position

df_1=df.copy()

df_1.insert(0,"col_0",[0,1,2,3,4])
df_1

   col_0  col_1  col_2    col_3
0      0      1    111    alpha
1      1      2    222    bravo
2      2      3    333  charlie
3      3      4    111      NaN
4      4      5    555      NaN