In [15]:
import pandas as pd
import numpy as np

In [16]:
arr_2d= np.arange(0,100).reshape(10,10)

In [17]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [18]:
index="r1 r2 r3 r4 r5 r6 r7 r8 r9 r10".split()
column="c1 c2 c3 c4 c5 c6 c7 c8 c9 c10".split()

In [19]:
index

['r1', 'r2', 'r3', 'r4', 'r5', 'r6', 'r7', 'r8', 'r9', 'r10']

In [20]:
column

['c1', 'c2', 'c3', 'c4', 'c5', 'c6', 'c7', 'c8', 'c9', 'c10']

In [24]:
df = pd.DataFrame(data=arr_2d,index=index,columns=column)
df

     c1  c2  c3  c4  c5  c6  c7  c8  c9  c10
r1    0   1   2   3   4   5   6   7   8    9
r2   10  11  12  13  14  15  16  17  18   19
r3   20  21  22  23  24  25  26  27  28   29
r4   30  31  32  33  34  35  36  37  38   39
r5   40  41  42  43  44  45  46  47  48   49
r6   50  51  52  53  54  55  56  57  58   59
r7   60  61  62  63  64  65  66  67  68   69
r8   70  71  72  73  74  75  76  77  78   79
r9   80  81  82  83  84  85  86  87  88   89
r10  90  91  92  93  94  95  96  97  98   99

In [25]:
#2ta column dhekar jonno
df[["c1","c2"]]

     c1  c2
r1    0   1
r2   10  11
r3   20  21
r4   30  31
r5   40  41
r6   50  51
r7   60  61
r8   70  71
r9   80  81
r10  90  91

In [32]:
type(df[["c3"]])

pandas.core.frame.DataFrame

In [34]:
#add new column addition
df["c1+c2"]=df["c1"]+df["c2"]

In [35]:
df

     c1  c2  c3  c4  c5  c6  c7  c8  c9  c10  c1+c2
r1    0   1   2   3   4   5   6   7   8    9      1
r2   10  11  12  13  14  15  16  17  18   19     21
r3   20  21  22  23  24  25  26  27  28   29     41
r4   30  31  32  33  34  35  36  37  38   39     61
r5   40  41  42  43  44  45  46  47  48   49     81
r6   50  51  52  53  54  55  56  57  58   59    101
r7   60  61  62  63  64  65  66  67  68   69    121
r8   70  71  72  73  74  75  76  77  78   79    141
r9   80  81  82  83  84  85  86  87  88   89    161
r10  90  91  92  93  94  95  96  97  98   99    181

In [38]:
df["new"]="b"
df

     c1  c2  c3  c4  c5  c6  c7  c8  c9  c10  c1+c2 new
r1    0   1   2   3   4   5   6   7   8    9      1   b
r2   10  11  12  13  14  15  16  17  18   19     21   b
r3   20  21  22  23  24  25  26  27  28   29     41   b
r4   30  31  32  33  34  35  36  37  38   39     61   b
r5   40  41  42  43  44  45  46  47  48   49     81   b
r6   50  51  52  53  54  55  56  57  58   59    101   b
r7   60  61  62  63  64  65  66  67  68   69    121   b
r8   70  71  72  73  74  75  76  77  78   79    141   b
r9   80  81  82  83  84  85  86  87  88   89    161   b
r10  90  91  92  93  94  95  96  97  98   99    181   b

In [40]:
#add in o number index 

va=[1,2,3,4,5,6,7,8,9,10]
df.insert(
    loc=0,
    column="c0",
    value=va
)
df

     c0  c1  c2  c3  c4  c5  c6  c7  c8  c9  c10  c1+c2 new
r1    1   0   1   2   3   4   5   6   7   8    9      1   b
r2    2  10  11  12  13  14  15  16  17  18   19     21   b
r3    3  20  21  22  23  24  25  26  27  28   29     41   b
r4    4  30  31  32  33  34  35  36  37  38   39     61   b
r5    5  40  41  42  43  44  45  46  47  48   49     81   b
r6    6  50  51  52  53  54  55  56  57  58   59    101   b
r7    7  60  61  62  63  64  65  66  67  68   69    121   b
r8    8  70  71  72  73  74  75  76  77  78   79    141   b
r9    9  80  81  82  83  84  85  86  87  88   89    161   b
r10  10  90  91  92  93  94  95  96  97  98   99    181   b

In [41]:
#remove column not permanent
df.drop("new",axis=1)

     c0  c1  c2  c3  c4  c5  c6  c7  c8  c9  c10  c1+c2
r1    1   0   1   2   3   4   5   6   7   8    9      1
r2    2  10  11  12  13  14  15  16  17  18   19     21
r3    3  20  21  22  23  24  25  26  27  28   29     41
r4    4  30  31  32  33  34  35  36  37  38   39     61
r5    5  40  41  42  43  44  45  46  47  48   49     81
r6    6  50  51  52  53  54  55  56  57  58   59    101
r7    7  60  61  62  63  64  65  66  67  68   69    121
r8    8  70  71  72  73  74  75  76  77  78   79    141
r9    9  80  81  82  83  84  85  86  87  88   89    161
r10  10  90  91  92  93  94  95  96  97  98   99    181

In [42]:
df

     c0  c1  c2  c3  c4  c5  c6  c7  c8  c9  c10  c1+c2 new
r1    1   0   1   2   3   4   5   6   7   8    9      1   b
r2    2  10  11  12  13  14  15  16  17  18   19     21   b
r3    3  20  21  22  23  24  25  26  27  28   29     41   b
r4    4  30  31  32  33  34  35  36  37  38   39     61   b
r5    5  40  41  42  43  44  45  46  47  48   49     81   b
r6    6  50  51  52  53  54  55  56  57  58   59    101   b
r7    7  60  61  62  63  64  65  66  67  68   69    121   b
r8    8  70  71  72  73  74  75  76  77  78   79    141   b
r9    9  80  81  82  83  84  85  86  87  88   89    161   b
r10  10  90  91  92  93  94  95  96  97  98   99    181   b

In [47]:
#permanent remove column
df.drop("c1" , axis=1 , inplace=True)

In [48]:
df

     c0  c2  c3  c4  c5  c6  c7  c8  c9  c10  c1+c2
r1    1   1   2   3   4   5   6   7   8    9      1
r2    2  11  12  13  14  15  16  17  18   19     21
r3    3  21  22  23  24  25  26  27  28   29     41
r4    4  31  32  33  34  35  36  37  38   39     61
r5    5  41  42  43  44  45  46  47  48   49     81
r6    6  51  52  53  54  55  56  57  58   59    101
r7    7  61  62  63  64  65  66  67  68   69    121
r8    8  71  72  73  74  75  76  77  78   79    141
r9    9  81  82  83  84  85  86  87  88   89    161
r10  10  91  92  93  94  95  96  97  98   99    181