In [4]:
import pandas as pd
import numpy as np

In [5]:
arr_2d= np.arange(0,100).reshape(10,10)

In [6]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [7]:
index="r1 r2 r3 r4 r5 r6 r7 r8 r9 r10".split()
column="c1 c2 c3 c4 c5 c6 c7 c8 c9 c10".split()

In [8]:
index

['r1', 'r2', 'r3', 'r4', 'r5', 'r6', 'r7', 'r8', 'r9', 'r10']

In [9]:
column

['c1', 'c2', 'c3', 'c4', 'c5', 'c6', 'c7', 'c8', 'c9', 'c10']

In [10]:
df = pd.DataFrame(data=arr_2d,index=index,columns=column)
df

     c1  c2  c3  c4  c5  c6  c7  c8  c9  c10
r1    0   1   2   3   4   5   6   7   8    9
r2   10  11  12  13  14  15  16  17  18   19
r3   20  21  22  23  24  25  26  27  28   29
r4   30  31  32  33  34  35  36  37  38   39
r5   40  41  42  43  44  45  46  47  48   49
r6   50  51  52  53  54  55  56  57  58   59
r7   60  61  62  63  64  65  66  67  68   69
r8   70  71  72  73  74  75  76  77  78   79
r9   80  81  82  83  84  85  86  87  88   89
r10  90  91  92  93  94  95  96  97  98   99

In [11]:
#2ta column dhekar jonno
df[["c1","c2"]]

     c1  c2
r1    0   1
r2   10  11
r3   20  21
r4   30  31
r5   40  41
r6   50  51
r7   60  61
r8   70  71
r9   80  81
r10  90  91

In [12]:
type(df[["c3"]])

pandas.core.frame.DataFrame

In [13]:
#add new column addition
df["c1+c2"]=df["c1"]+df["c2"]

In [14]:
df

     c1  c2  c3  c4  c5  c6  c7  c8  c9  c10  c1+c2
r1    0   1   2   3   4   5   6   7   8    9      1
r2   10  11  12  13  14  15  16  17  18   19     21
r3   20  21  22  23  24  25  26  27  28   29     41
r4   30  31  32  33  34  35  36  37  38   39     61
r5   40  41  42  43  44  45  46  47  48   49     81
r6   50  51  52  53  54  55  56  57  58   59    101
r7   60  61  62  63  64  65  66  67  68   69    121
r8   70  71  72  73  74  75  76  77  78   79    141
r9   80  81  82  83  84  85  86  87  88   89    161
r10  90  91  92  93  94  95  96  97  98   99    181

In [15]:
df["new"]="b"
df

     c1  c2  c3  c4  c5  c6  c7  c8  c9  c10  c1+c2 new
r1    0   1   2   3   4   5   6   7   8    9      1   b
r2   10  11  12  13  14  15  16  17  18   19     21   b
r3   20  21  22  23  24  25  26  27  28   29     41   b
r4   30  31  32  33  34  35  36  37  38   39     61   b
r5   40  41  42  43  44  45  46  47  48   49     81   b
r6   50  51  52  53  54  55  56  57  58   59    101   b
r7   60  61  62  63  64  65  66  67  68   69    121   b
r8   70  71  72  73  74  75  76  77  78   79    141   b
r9   80  81  82  83  84  85  86  87  88   89    161   b
r10  90  91  92  93  94  95  96  97  98   99    181   b

In [16]:
#add in o number index 

va=[1,2,3,4,5,6,7,8,9,10]
df.insert(
    loc=0,
    column="c0",
    value=va
)
df

     c0  c1  c2  c3  c4  c5  c6  c7  c8  c9  c10  c1+c2 new
r1    1   0   1   2   3   4   5   6   7   8    9      1   b
r2    2  10  11  12  13  14  15  16  17  18   19     21   b
r3    3  20  21  22  23  24  25  26  27  28   29     41   b
r4    4  30  31  32  33  34  35  36  37  38   39     61   b
r5    5  40  41  42  43  44  45  46  47  48   49     81   b
r6    6  50  51  52  53  54  55  56  57  58   59    101   b
r7    7  60  61  62  63  64  65  66  67  68   69    121   b
r8    8  70  71  72  73  74  75  76  77  78   79    141   b
r9    9  80  81  82  83  84  85  86  87  88   89    161   b
r10  10  90  91  92  93  94  95  96  97  98   99    181   b

In [17]:
#remove column not permanent
df.drop("new",axis=1)

     c0  c1  c2  c3  c4  c5  c6  c7  c8  c9  c10  c1+c2
r1    1   0   1   2   3   4   5   6   7   8    9      1
r2    2  10  11  12  13  14  15  16  17  18   19     21
r3    3  20  21  22  23  24  25  26  27  28   29     41
r4    4  30  31  32  33  34  35  36  37  38   39     61
r5    5  40  41  42  43  44  45  46  47  48   49     81
r6    6  50  51  52  53  54  55  56  57  58   59    101
r7    7  60  61  62  63  64  65  66  67  68   69    121
r8    8  70  71  72  73  74  75  76  77  78   79    141
r9    9  80  81  82  83  84  85  86  87  88   89    161
r10  10  90  91  92  93  94  95  96  97  98   99    181

In [18]:
df

     c0  c1  c2  c3  c4  c5  c6  c7  c8  c9  c10  c1+c2 new
r1    1   0   1   2   3   4   5   6   7   8    9      1   b
r2    2  10  11  12  13  14  15  16  17  18   19     21   b
r3    3  20  21  22  23  24  25  26  27  28   29     41   b
r4    4  30  31  32  33  34  35  36  37  38   39     61   b
r5    5  40  41  42  43  44  45  46  47  48   49     81   b
r6    6  50  51  52  53  54  55  56  57  58   59    101   b
r7    7  60  61  62  63  64  65  66  67  68   69    121   b
r8    8  70  71  72  73  74  75  76  77  78   79    141   b
r9    9  80  81  82  83  84  85  86  87  88   89    161   b
r10  10  90  91  92  93  94  95  96  97  98   99    181   b

In [19]:
#permanent remove column
df.drop("c1" , axis=1 , inplace=True)

In [24]:
#show row
df.loc[["r9"]]

    c0  c2  c3  c4  c5  c6  c7  c8  c9  c10  c1+c2 new
r9   9  81  82  83  84  85  86  87  88   89    161   b

In [26]:
#permanent remove column
df.drop("new" , axis=1 , inplace=True)

In [27]:
df

     c0  c2  c3  c4  c5  c6  c7  c8  c9  c10  c1+c2
r1    1   1   2   3   4   5   6   7   8    9      1
r2    2  11  12  13  14  15  16  17  18   19     21
r3    3  21  22  23  24  25  26  27  28   29     41
r4    4  31  32  33  34  35  36  37  38   39     61
r5    5  41  42  43  44  45  46  47  48   49     81
r6    6  51  52  53  54  55  56  57  58   59    101
r7    7  61  62  63  64  65  66  67  68   69    121
r8    8  71  72  73  74  75  76  77  78   79    141
r9    9  81  82  83  84  85  86  87  88   89    161
r10  10  91  92  93  94  95  96  97  98   99    181

In [28]:
df>5

        c0     c2     c3     c4     c5     c6    c7    c8    c9   c10  c1+c2
r1   False  False  False  False  False  False  True  True  True  True  False
r2   False   True   True   True   True   True  True  True  True  True   True
r3   False   True   True   True   True   True  True  True  True  True   True
r4   False   True   True   True   True   True  True  True  True  True   True
r5   False   True   True   True   True   True  True  True  True  True   True
r6    True   True   True   True   True   True  True  True  True  True   True
r7    True   True   True   True   True   True  True  True  True  True   True
r8    True   True   True   True   True   True  True  True  True  True   True
r9    True   True   True   True   True   True  True  True  True  True   True
r10   True   True   True   True   True   True  True  True  True  True   True

In [29]:
mask=df%3==0
mask

,c0,c2,c3,c4,c5,c6,c7,c8,c9,c10,c1+c2
r1,False,False,False,True,False,False,True,False,False,True,False
r2,False,False,True,False,False,True,False,False,True,False,True
r3,True,True,False,False,True,False,False,True,False,False,False
r4,False,False,False,True,False,False,True,False,False,True,False
r5,False,False,True,False,False,True,False,False,True,False,True
r6,True,True,False,False,True,False,False,True,False,False,False
r7,False,False,False,True,False,False,True,False,False,True,False
r8,False,False,True,False,False,True,False,False,True,False,True
r9,True,True,False,False,True,False,False,True,False,False,False
r10,False,False,False,True,False,False,True,False,False,True,False

In [30]:
df[mask]

      c0    c2    c3    c4    c5    c6    c7    c8    c9   c10  c1+c2
r1   NaN   NaN   NaN   3.0   NaN   NaN   6.0   NaN   NaN   9.0    NaN
r2   NaN   NaN  12.0   NaN   NaN  15.0   NaN   NaN  18.0   NaN   21.0
r3   3.0  21.0   NaN   NaN  24.0   NaN   NaN  27.0   NaN   NaN    NaN
r4   NaN   NaN   NaN  33.0   NaN   NaN  36.0   NaN   NaN  39.0    NaN
r5   NaN   NaN  42.0   NaN   NaN  45.0   NaN   NaN  48.0   NaN   81.0
r6   6.0  51.0   NaN   NaN  54.0   NaN   NaN  57.0   NaN   NaN    NaN
r7   NaN   NaN   NaN  63.0   NaN   NaN  66.0   NaN   NaN  69.0    NaN
r8   NaN   NaN  72.0   NaN   NaN  75.0   NaN   NaN  78.0   NaN  141.0
r9   9.0  81.0   NaN   NaN  84.0   NaN   NaN  87.0   NaN   NaN    NaN
r10  NaN   NaN   NaN  93.0   NaN   NaN  96.0   NaN   NaN  99.0    NaN

In [32]:
#condition
df[df["c0"]>5]

     c0  c2  c3  c4  c5  c6  c7  c8  c9  c10  c1+c2
r6    6  51  52  53  54  55  56  57  58   59    101
r7    7  61  62  63  64  65  66  67  68   69    121
r8    8  71  72  73  74  75  76  77  78   79    141
r9    9  81  82  83  84  85  86  87  88   89    161
r10  10  91  92  93  94  95  96  97  98   99    181

In [34]:
df[df["c0"]>5][["c0","c2"]]

     c0  c2
r6    6  51
r7    7  61
r8    8  71
r9    9  81
r10  10  91

In [36]:
df[(df["c0"]>4)&(df["c0"]<9)]

    c0  c2  c3  c4  c5  c6  c7  c8  c9  c10  c1+c2
r5   5  41  42  43  44  45  46  47  48   49     81
r6   6  51  52  53  54  55  56  57  58   59    101
r7   7  61  62  63  64  65  66  67  68   69    121
r8   8  71  72  73  74  75  76  77  78   79    141