In [22]:
import pandas as pd
import numpy as np

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.

In [23]:
dic={"a":[1,2,np.nan,4,np.nan],
     "b":[np.nan,np.nan,np.nan,np.nan,np.nan],
     "c":[11,12,13,14,15],
     "d":[16,np.nan,np.nan,19,20]
    }
df=pd.DataFrame(dic)
df

     a   b   c     d
0  1.0 NaN  11  16.0
1  2.0 NaN  12   NaN
2  NaN NaN  13   NaN
3  4.0 NaN  14  19.0
4  NaN NaN  15  20.0

In [24]:
type(df)

pandas.core.frame.DataFrame

<h3>check the null value</h3><br><p>using isnull(),isna(),notnull()</p>

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   a       3 non-null      float64
 1   b       0 non-null      float64
 2   c       5 non-null      int64
 3   d       3 non-null      float64
dtypes: float64(3), int64(1)
memory usage: 292.0 bytes

In [26]:
df.isnull()

       a     b      c      d
0  False  True  False  False
1  False  True  False   True
2   True  True  False   True
3  False  True  False  False
4   True  True  False  False

In [27]:
df.isnull().sum()

a    2
b    5
c    0
d    2
dtype: int64

In [28]:
df["d"].isnull().sum()

np.int64(2)

In [9]:
#row jonno
df.loc[1].isnull().sum()

np.int64(2)

In [11]:
df["a"].mean()

np.float64(2.3333333333333335)

In [19]:
df["b"].sum()

np.float64(0.0)

In [17]:
df.loc[1].sum()

np.float64(14.0)

In [18]:
df

     a   b   c     d
0  1.0 NaN  11  16.0
1  2.0 NaN  12   NaN
2  NaN NaN  13   NaN
3  4.0 NaN  14  19.0
4  NaN NaN  15  20.0

In [20]:
#removing the null value rows
df.dropna(axis=0)

Empty DataFrame
Columns: [a, b, c, d]
Index: []

In [21]:
#remove column of null value
df.dropna(axis=1)

    c
0  11
1  12
2  13
3  14
4  15

<h3>thresh je koita dibo oitar kom value thakte delete hobe</h3>