In [2]:
import pandas as pd
import numpy as np

In [3]:
dic={"a":[1,2,np.nan,4,np.nan],
     "b":[np.nan,np.nan,np.nan,np.nan,np.nan],
     "c":[11,12,13,14,15],
     "d":[16,np.nan,np.nan,19,20]
    }
df=pd.DataFrame(dic)
df

     a   b   c     d
0  1.0 NaN  11  16.0
1  2.0 NaN  12   NaN
2  NaN NaN  13   NaN
3  4.0 NaN  14  19.0
4  NaN NaN  15  20.0

In [4]:
type(df)

pandas.core.frame.DataFrame

<h3>check the null value</h3><br><p>using isnull(),isna(),notnull()</p>

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   a       3 non-null      float64
 1   b       0 non-null      float64
 2   c       5 non-null      int64
 3   d       3 non-null      float64
dtypes: float64(3), int64(1)
memory usage: 292.0 bytes

In [6]:
df.isnull()

       a     b      c      d
0  False  True  False  False
1  False  True  False   True
2   True  True  False   True
3  False  True  False  False
4   True  True  False  False

In [7]:
df.isnull().sum()

a    2
b    5
c    0
d    2
dtype: int64

In [8]:
df["d"].isnull().sum()

np.int64(2)

In [9]:
#row jonno
df.loc[1].isnull().sum()

np.int64(2)

In [10]:
df["a"].mean()

np.float64(2.3333333333333335)

In [11]:
df["b"].sum()

np.float64(0.0)

In [12]:
df.loc[1].sum()

np.float64(14.0)

In [13]:
df

     a   b   c     d
0  1.0 NaN  11  16.0
1  2.0 NaN  12   NaN
2  NaN NaN  13   NaN
3  4.0 NaN  14  19.0
4  NaN NaN  15  20.0

In [14]:
#removing the null value rows
df.dropna(axis=0)

Empty DataFrame
Columns: [a, b, c, d]
Index: []

In [15]:
#remove column of null value
df.dropna(axis=1)

    c
0  11
1  12
2  13
3  14
4  15

<h3>thresh je koita dibo oitar kom value thakte delete hobe</h3>

In [16]:
df.dropna(thresh=3,axis=1)

     a   c     d
0  1.0  11  16.0
1  2.0  12   NaN
2  NaN  13   NaN
3  4.0  14  19.0
4  NaN  15  20.0

In [17]:
#fill the null value
df.fillna(value=2)

     a    b   c     d
0  1.0  2.0  11  16.0
1  2.0  2.0  12   2.0
2  2.0  2.0  13   2.0
3  4.0  2.0  14  19.0
4  2.0  2.0  15  20.0

In [19]:
df.fillna(value=1)

     a    b   c     d
0  1.0  1.0  11  16.0
1  2.0  1.0  12   1.0
2  1.0  1.0  13   1.0
3  4.0  1.0  14  19.0
4  1.0  1.0  15  20.0

In [20]:
df["a"].fillna(value=df["a"].mean())

0    1.000000
1    2.000000
2    2.333333
3    4.000000
4    2.333333
Name: a, dtype: float64

In [21]:
#forword fill method = method="ffill"
df.fillna(method="ffill")

/var/folders/8m/z55hbs5179lfqczhr02ylx980000gn/T/ipykernel_17865/704413205.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="ffill")

     a   b   c     d
0  1.0 NaN  11  16.0
1  2.0 NaN  12  16.0
2  2.0 NaN  13  16.0
3  4.0 NaN  14  19.0
4  4.0 NaN  15  20.0

In [22]:
df

     a   b   c     d
0  1.0 NaN  11  16.0
1  2.0 NaN  12   NaN
2  NaN NaN  13   NaN
3  4.0 NaN  14  19.0
4  NaN NaN  15  20.0

In [23]:
#backword fill
df.fillna(method="bfill")

/var/folders/8m/z55hbs5179lfqczhr02ylx980000gn/T/ipykernel_17865/3286878099.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="bfill")

     a   b   c     d
0  1.0 NaN  11  16.0
1  2.0 NaN  12  19.0
2  4.0 NaN  13  19.0
3  4.0 NaN  14  19.0
4  NaN NaN  15  20.0

In [26]:
from sklearn.impute import SimpleImputer

In [28]:
df2=df.copy()
df2

     a   b   c     d
0  1.0 NaN  11  16.0
1  2.0 NaN  12   NaN
2  NaN NaN  13   NaN
3  4.0 NaN  14  19.0
4  NaN NaN  15  20.0

In [30]:
#fixed change
impute=SimpleImputer(strategy="constant",fill_value=-1)
df2["a"]=impute.fit_transform(df2[["a"]])
df2

     a   b   c     d
0  1.0 NaN  11  16.0
1  2.0 NaN  12   NaN
2 -1.0 NaN  13   NaN
3  4.0 NaN  14  19.0
4 -1.0 NaN  15  20.0

In [32]:
impute=SimpleImputer(strategy="mean")
df2["d"]=impute.fit_transform(df2[["d"]])
df2

     a   b   c          d
0  1.0 NaN  11  16.000000
1  2.0 NaN  12  18.333333
2 -1.0 NaN  13  18.333333
3  4.0 NaN  14  19.000000
4 -1.0 NaN  15  20.000000

In [34]:
impute=SimpleImputer(strategy="median")
df2["d"]=impute.fit_transform(df2[["d"]])
df2

     a   b     c          d
0  1.0 NaN  11.0  16.000000
1  2.0 NaN  12.0  18.333333
2 -1.0 NaN  13.0  18.333333
3  4.0 NaN  14.0  19.000000
4 -1.0 NaN  15.0  20.000000

In [37]:
dff={"A":[1,2,np.nan,3,np.nan],
     "B":[np.nan,np.nan,np.nan,np.nan,np.nan],
    "C":[11,12,13,14,15],
    "D":[16,18,np.nan,np.nan,18]
    
}

In [38]:
df3=pd.DataFrame(dff)
df3

     A   B   C     D
0  1.0 NaN  11  16.0
1  2.0 NaN  12  18.0
2  NaN NaN  13   NaN
3  3.0 NaN  14   NaN
4  NaN NaN  15  18.0

In [40]:
impute=SimpleImputer(strategy="most_frequent")
df3["D"]=impute.fit_transform(df3[["D"]])
df3

     A   B   C     D
0  1.0 NaN  11  16.0
1  2.0 NaN  12  18.0
2  NaN NaN  13  18.0
3  3.0 NaN  14  18.0
4  NaN NaN  15  18.0

In [42]:
from sklearn.impute import KNNImputer

In [43]:
df3=df3.copy()
df3

     A   B   C     D
0  1.0 NaN  11  16.0
1  2.0 NaN  12  18.0
2  NaN NaN  13  18.0
3  3.0 NaN  14  18.0
4  NaN NaN  15  18.0

In [45]:
knn=KNNImputer(n_neighbors=3,weights="uniform")
df3=knn.fit_transform(df3)
df3

array([[ 1., 11., 16.],
       [ 2., 12., 18.],
       [ 2., 13., 18.],
       [ 3., 14., 18.],
       [ 2., 15., 18.]])

In [47]:
d={
    "store":["walton","walton","volvo","volvo","singer","singer"],
    "customer":["jayanto","sabit","kabbo","tanin","ahim","fuad"],
    "sales":[150,120,300,220,430,110]
}
df=pd.DataFrame(d)
df

    store customer  sales
0  walton  jayanto    150
1  walton    sabit    120
2   volvo    kabbo    300
3   volvo    tanin    220
4  singer     ahim    430
5  singer     fuad    110

In [48]:
#group by store sum of sales
df.groupby("store")[["sales"]].sum()

        sales
store
singer    540
volvo     520
walton    270

In [49]:
df.groupby("store")[["sales"]].mean()

        sales
store
singer  270.0
volvo   260.0
walton  135.0

In [50]:
df.groupby("store")[["sales"]].median()

        sales
store
singer  270.0
volvo   260.0
walton  135.0